# Create a program that will play the "cows and bulls" game with the user.
# The game works like this:

#  - Randomly generate a 4-digit number.
#  - Ask the user to guess a 4-digit number.
#  - For every digit that the user guessed correctly in the correct place,
#     they have a "cow".
#  - For every digit the user guessed correctly, but not in the correct
#     place is a "bull."
#  - Every time the user makes a guess, tell them how many "cows" and
#     "bulls" they have.
#  - Once the user guesses the correct number, the game is over.
#  - Keep track of the number of guesses the user makes throughout the game
#     and tell the user at the end.

# An example run could look like this: (the number generated by the computer is 1038)
'''
  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ... <user keeps guessing> ...
  >>> 1083
  2 cow, 2 bulls
  >>> 1038
  Congratulations! That is correct!
  It took 14 guesses to get the correct number.
'''
import random

answer = random.randint(1000, 9999)
answer = 7216
answer = list(str(answer))

print("Welcome to the Cows and Bulls Game!")

guess_count = 0
while True:
  guess = (input("Enter a number: "))
  guess = list(str(guess))
  guess_count += 1
  cows = 0
  bulls = 0

  for i in range(4):  
    if guess == answer:
      print(f"CORRECT! It took {guess_count} guesses to get the correct number.")
      exit()

      # if bull
    if guess[i] != answer[i] and guess[i] in answer:
      bulls += 1

      # if cow
    if guess[i] == answer[i]:
      cows += 1

  print("cows: ", cows)

  print("bulls: ", bulls)
    



    
    
    
   